### ISSUE TITLE
VRCFT 5.0 - Native Eye Tracking support?

### ISSUE THREAD

**Issue by h0yer** [m3gagluk/VRCFTVarjoModule#9]
Heya!

Would be great if you could update your Varjo plugin to support the recent changes in VRCFT.

Cheers!

**Comment by m3gagluk** [comment]
Hi! @Chickenbreadlp has already updated the module in their fork https://github.com/Chickenbreadlp/VRCFTVarjoModule/tree/vrcft_5 - for now they're the main maintainer of the module.
The compiled module binaries are temprorarily available only in the VRCFT Discord but they'll probably be properly released soon if no new issues arise.

**Comment by Chickenbreadlp** [comment]
I wanted to make sure that my changes worked well first, which is why the updated module is currently only available in the VRCFT Discord ([here btw](https://discord.com/channels/849300336128032789/1100138444186980413))
It does seem to work pretty well, so I'll hopefully get the time to work with Ben or Azmidi to get the module wrapped up and included into the new module registry that was added with VRCFT 5.0.
Reason I only consider the bare dll as a beta or pre-release is because the way of just placing a dll file in the CustomModules folder is now only meant for module development and beta distribution...

UPDATE: I've now created a pre-release on my fork with the updated dll [here](https://github.com/Chickenbreadlp/VRCFTVarjoModule/releases/tag/4.0.0-beta2). Mostly just for the people who don't have Discord really...

**Comment by h0yer** [comment]
Splendid, thanks for the info :)
